### ISSUE TITLE
pytube not working giving such error

### ISSUE THREAD

**Issue by Umashankar1411** [Umashankar1411/UGT#2]
C:\Users\HP\PycharmProjects\YoutubeVidDownloader\venv\Scripts\python.exe C:/Users/HP/PycharmProjects/YoutubeVidDownloader/Ytube_main.py
Traceback (most recent call last):
  File "C:/Users/HP/PycharmProjects/YoutubeVidDownloader/Ytube_main.py", line 1, in <module>
    from pytube import *
  File "C:\Users\HP\PycharmProjects\YoutubeVidDownloader\venv\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\HP\PycharmProjects\YoutubeVidDownloader\venv\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\HP\PycharmProjects\YoutubeVidDownloader\venv\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\HP\PycharmProjects\YoutubeVidDownloader\venv\lib\site-packages\pytube\compat.py)

Process finished with exit code 1

**Comment by Umashankar1411** [comment]
by installing pyttsx3 version 2.71 the package has been installed
